title: Luca Fontaine
logo: "/images/Luca2.JPG?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  <a href="https://www.linkedin.com/in/lucafontaine/">LinkedIn</a> 
  <br>
  <a href="pdf/RESMUEÌ.2023.pdf/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/LucaF20">GitHub</a>  

  
theme: jekyll-theme-minimal
